context.modules = [
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Mixy Desktop Audio"
            capture.props = {
                node.name = "mixy_desktop_sink"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.passive = true
            }
        }
    }
    {
        name = libpipewire-module-loopback
        args = {
            node.description = "Mixy Chat Audio"
            capture.props = {
                node.name = "mixy_chat_sink"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.passive = true
            }
        }
    }
]
